# Generated by Django 6.0.3 on 2026-03-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('port', models.PositiveIntegerField(default=4370)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zk_user_id', models.PositiveIntegerField(help_text='ZK device user ID')),
                ('finger_id', models.PositiveSmallIntegerField(help_text='Finger index 0-9 (0=right thumb, 1=right index, etc.)')),
                ('template', models.BinaryField(help_text='Raw ZKTeco fingerprint template binary data')),
                ('quality', models.PositiveSmallIntegerField(default=0, help_text='Template quality score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backed_up_from', models.ForeignKey(blank=True, help_text='Device this template was pulled from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_backups', to='devices.device')),
            ],
            options={
                'db_table': 'fingerprint_templates',
                'ordering': ['zk_user_id', 'finger_id'],
                'unique_together': {('zk_user_id', 'finger_id')},
            },
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zk_user_id', models.PositiveIntegerField(help_text='User ID as stored on the ZKTeco device')),
                ('person_type', models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('punch_time', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False, help_text='True once converted to an AttendanceRecord')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_logs', to='devices.device')),
            ],
            options={
                'db_table': 'punch_logs',
                'ordering': ['punch_time'],
                'indexes': [models.Index(fields=['zk_user_id', 'punch_time'], name='punch_logs_zk_user_3f1952_idx'), models.Index(fields=['is_processed'], name='punch_logs_is_proc_a51db0_idx')],
                'unique_together': {('device', 'zk_user_id', 'punch_time')},
            },
        ),
    ]
