# Generated by Django 6.0.3 on 2026-03-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zk_user_id', models.PositiveIntegerField(help_text='ZK device user ID')),
                ('finger_id', models.PositiveSmallIntegerField(help_text='Finger index 0-9 (0=right thumb, 1=right index, etc.)')),
                ('template', models.BinaryField(help_text='Raw ZKTeco fingerprint template binary data')),
                ('quality', models.PositiveSmallIntegerField(default=0, help_text='Template quality score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backed_up_from', models.ForeignKey(blank=True, help_text='Device this template was pulled from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint_backups', to='devices.device')),
            ],
            options={
                'db_table': 'fingerprint_templates',
                'ordering': ['zk_user_id', 'finger_id'],
                'unique_together': {('zk_user_id', 'finger_id')},
            },
        ),
    ]
