# Generated by Django 6.0.3 on 2026-03-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='NonSchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('day_type', models.CharField(choices=[('holiday', 'Public Holiday'), ('closure', 'Ad-hoc Closure')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'non_school_days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.academicyear')),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['academic_year', 'term_number'],
                'unique_together': {('academic_year', 'term_number')},
            },
        ),
        migrations.CreateModel(
            name='LateThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('saturday', 'Saturday')], max_length=20)),
                ('cutoff_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.ForeignKey(blank=True, help_text='Leave blank to apply school-wide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_thresholds', to='people.stream')),
            ],
            options={
                'db_table': 'late_thresholds',
                'unique_together': {('day_type', 'applies_to')},
            },
        ),
        migrations.CreateModel(
            name='SchoolDayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('stream', models.ForeignKey(blank=True, help_text='Leave blank to apply school-wide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_configs', to='people.stream')),
            ],
            options={
                'db_table': 'school_day_configs',
                'unique_together': {('stream', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='SchoolWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.term')),
            ],
            options={
                'db_table': 'school_weeks',
                'ordering': ['term', 'week_number'],
                'unique_together': {('term', 'week_number')},
            },
        ),
    ]
